import type { Metadata } from 'next'
import './globals.css'
import { ReduxProvider } from '@/store/provider'
import React from 'react'
import { Header } from '@/widgets/header/ui/Header'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <head>
                <link
                    rel="stylesheet"
                    href="https://fonts.googleapis.com/icon?family=Material+Icons"
                />
            </head>
            <body>
                <ReduxProvider>
                    <Header />
                    <main>{children}</main>
                </ReduxProvider>
            </body>
        </html>
    )
}
