# Этот комментарий для принудительного обновления

name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Yandex Cloud CLI
        uses: yandex-cloud/yc-actions/yc-cli-install@v1.2.0

      - name: Login to Yandex Container Registry
        id: login-cr
        uses: yandex-cloud/yc-actions/yc-cr-login@v1.2.0
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_KEY_JSON }}

      - name: Build, tag, and push image to Yandex Container Registry
        run: |
          docker build -t ${{ steps.login-cr.outputs.registry-address }}/${{ secrets.YC_REGISTRY_ID }}/my-next-app:${{ github.sha }} .
          docker push ${{ steps.login-cr.outputs.registry-address }}/${{ secrets.YC_REGISTRY_ID }}/my-next-app:${{ github.sha }}

      - name: Deploy new Serverless Container revision
        uses: yandex-cloud/yc-actions/yc-sls-container-deploy@v1.2.0
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_KEY_JSON }}
          container-id: ${{ secrets.YC_CONTAINER_ID }}
          image-url: ${{ steps.login-cr.outputs.registry-address }}/${{ secrets.YC_REGISTRY_ID }}/my-next-app:${{ github.sha }}