name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Yandex CLI
        run: |
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH

      - name: Auth with service account
        run: |
          echo '${{ secrets.YC_SA_KEY_JSON }}' > key.json
          yc config set service-account-key key.json
          yc config list

      - name: Deploy script
        run: |
          # Твоя логика: Docker push, yc compute create и т.п.
          yc compute instance list
