name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Yandex Cloud CLI
        run: |
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH

      - name: Authorize with Yandex Cloud
        run: |
          echo '${{ secrets.YC_SA_KEY_JSON }}' > key.json
          yc config set service-account-key key.json
          yc config list

      - name: Login to Yandex Container Registry
        run: |
          yc container registry configure-docker

      - name: Build, tag, and push image to Yandex Container Registry
        env:
          REGISTRY: crp...your_registry_id_here
        run: |
          IMAGE=${REGISTRY}/my-next-app:${{ github.sha }}
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy to Serverless Containers
        run: |
          IMAGE=${{ secrets.YC_REGISTRY_ID }}/my-next-app:${{ github.sha }}
          yc serverless container revision deploy \
            --container-id=${{ secrets.YC_CONTAINER_ID }} \
            --image=$IMAGE \
            --memory=512M \
            --cores=1 \
            --execution-timeout=30s \
            --concurrency=4
